### ISSUE TITLE
ForgeMicroblock Material with id already registered

### ISSUE THREAD

**Issue by superzanti** [superzanti/TheVerse#5]
Starting on line 11303 of fml-client-latest.log

```
[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:factoryblock2 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:factoryblock2_1 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:factoryblock2_2 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:factoryblock2_3 is already registered.
```

line 12008

```
[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:voidstoneRunic_1 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:voidstoneRunic_2 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:voidstoneRunic_3 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:voidstoneRunic_4 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:voidstoneRunic_5 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:voidstoneRunic_6 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:voidstoneRunic_7 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:voidstoneRunic_8 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:voidstoneRunic_9 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:voidstoneRunic_10 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:voidstoneRunic_11 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:voidstoneRunic_12 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:voidstoneRunic_13 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:voidstoneRunic_14 is already registered.

[15:33:48] [Client thread/ERROR] [ForgeMicroblock/ForgeMicroblock]: Material with id chisel:voidstoneRunic_15 is already registered.
```

**Comment by Weikardzaena** [comment]
I'll take a look at this one

**Comment by Weikardzaena** [comment]
Done!

**Comment by superzanti** [comment]
Fixed in #27

**Comment by superzanti** [comment]
Looks like this is still an issue but with other blocks. Taking out the voidstone now gives me an error in game:

http://i.imgur.com/YddZfSc.png

**Comment by Weikardzaena** [comment]
The above error is fixed by deleting the voidstone.zs script that fixes the recipe for that block.  I honestly don't think that script existed when I made the first PR, and was added in some time after the big reset.

**Comment by superzanti** [comment]
Yeah I found out that If I change the voidstone back to true in the config the error goes away. I forgot to close this but it's fixed in the latest commit.

The script was added because it's part of the direwolf20 pack.

**Comment by Weikardzaena** [comment]
Oh so the microblocks error is also fixed with the direwolf20 pack?

**Comment by superzanti** [comment]
Oh no, we're still having the microblocks id errors.

**Comment by Weikardzaena** [comment]
Same error appears in the FTB Direwolf20 mod pack, so can probably close this issue as it seems not that important.
